config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    #com / o argumento ja é recebido no controller como subject_id
    get 'subject/:subject_id', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
  end

  namespace :admins_backoffice do
    get 'welcome/index' #Dashboard
    resources :admins
    resources :subjects
    resources :questions
  end
  
  #skip exclui rota para registrar novos admins 
  devise_for :admins, skip: [:registrations]
  devise_for :users
  
  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #Kaminari paginator
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  #atualiza o banco apos adicionar a coluna para contagem de assunto.(counter_cache)
  # x = Subject.last
  #Subject.reset_counters(x.id, :questions)

  has_many :answers

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  
  #paginates_per 8
  
  #scope são usadas quando é necessario fazer alguma pesquisa no model
  scope :list_questions_params, ->(page_params){
    Question.includes(:answers, :subject)
            .where('lower(description) LIKE ?', "%#{page_params.downcase}%")
  }
  
  scope :list_questions, ->{
    Question.includes(:answers, :subject)
            .order('created_at desc')
  }

  scope :list_subject_params, ->(page_params, subject_id){
    Question.includes(:answers, :subject)
            .where(subject_id: subject_id)
  }
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    [self.first_name, self.last_name].join(" ")
  end
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]
  
  def index
  #código '.page' referente a páginação com kaminari
    @admins = Admin.all.page(params[:page])
  end

  #rails consegue identificar que a rota para um Hash que está em branco é new
  def new
    @admin = Admin.new
  end
  
  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso"
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluido com sucesso"
    else
      render :index
    end
  end

  private
  def params_admin
    #segurança permito que as informações abaixo sejam recebidas pelo controller
    params_admin = params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end  

end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller? && resource_class == Admin
      'admin_devise'
    elsif devise_controller? && resource_class == User
      'user_devise'
    else
      'application'
    end
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    admin_path
  end

end

app/controllers/site/answer_controller.rb
module Site
  class AnswerController < SiteController
    
    def question
      @answer = Answer.find(params[:answer_id])
    end
  end
end

app/controllers/site/search_controller.rb
module Site
  class SearchController < SiteController
    
    def questions
      questions = Question.list_questions_params(params[:term])

      @questions = paginate_questions(questions)
    end

    def subject
      questions = Question.list_subject_params(params[:term], params[:subject_id])

      @questions = paginate_questions(questions)
    end

    private

    def paginate_questions(questions)
      Kaminari.paginate_array(questions).page(params[:page]).per(8)
    end
  end
end

app/controllers/site/welcome_controller.rb
module Site
  class WelcomeController < SiteController
    
    def index
      questions = Question.list_questions

      @questions = paginate_questions(questions)
    end
    
    private

    def paginate_questions(questions)
      Kaminari.paginate_array(questions).page(params[:page]).per(8)
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/profile_controller.rb
module UsersBackoffice
  class ProfileController < UsersBackofficeController

    def edit
      @user = User.find(current_user.id)
    end
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/site/search/questions.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Time to answer</title>
  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="plugins/bootstrap/css/bootstrap.min.css">
  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="stylesheets/style.css">
</head>
<body>
<header class="navigation">
	<nav class="navbar navbar-expand-lg  py-4" id="navbar">
		<div class="container">
		  <a class="navbar-brand">
		  	Time to<span> Answer.</span>
		  </a>
		  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
			<span class="fa fa-bars"></span>
		  </button>
		  <div class="collapse navbar-collapse text-center" id="navbarsExample09">
				<%= form_with(url: site_search_path, local: true, method: :get, class: "form-inline") do |form|%>
					<%= form.text_field :term, class: "form-control mr-sm-2", type: "search", placeholder: "Search" %>
					<button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
				<% end %>
			<ul class="navbar-nav ml-auto">
			<% unless user_signed_in? %>
				<li class="nav-item active">
					<%= link_to 'Entrar', new_user_session_path , class:"nav-link"%>
			  </li>
			  <li class="nav-item">
					<%= link_to 'Cadastrar-se', new_user_registration_path, class: "nav-link"%>
				</li>
			<% else %>
			   <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown05">
						<%= link_to users_backoffice_welcome_index_path do %>
							<i class="dropdown-item">Perfil</i>
						<% end %>
						<%= link_to destroy_user_session_path, method: :delete do  %>
							<i class="dropdown-item">Sair</i>
						<% end %>
					</ul>
			  </li>
				<% end %>
			</ul>
		  </div>
		</div>
	</nav>
</header>
<div class="main-wrapper ">
<section class="slider">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 col-md-10">
				<div class="block">
					<span class="d-block mb-3 text-white text-capitalize">Aplicativo de Perguntas e respostas</span>
					<h1 class="animated fadeInUp mb-5">Our work is <br>presentation of our <br>capabilities.</h1>
				</div>
			</div>
		</div>
    <%= render partial: 'shared/questions' %>
	</div>	
</section>
    <!-- Main jQuery -->
    <script src="plugins/jquery/jquery.js"></script>
    <script src="js/contact.js"></script>
    <!-- Bootstrap 4.3.1 -->
    <script src="plugins/bootstrap/js/popper.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.min.js"></script>
   <!--  Magnific Popup-->
    <script src="plugins/magnific-popup/dist/jquery.magnific-popup.min.js"></script>
    <!-- Slick Slider -->
    <script src="plugins/slick-carousel/slick/slick.min.js"></script>
    <!-- Counterup -->
    <script src="plugins/counterup/jquery.waypoints.min.js"></script>
    <script src="plugins/counterup/jquery.counterup.min.js"></script>  
    
    <script src="js/script.js"></script>

</body>
</html>
   

app/views/site/search/subject.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Time to answer</title>
  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="plugins/bootstrap/css/bootstrap.min.css">
  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="stylesheets/style.css">
</head>
<body>
<header class="navigation">
	<nav class="navbar navbar-expand-lg  py-4" id="navbar">
		<div class="container">
		  <a class="navbar-brand">
		  	Time to<span> Answer.</span>
		  </a>
		  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
			<span class="fa fa-bars"></span>
		  </button>
		  <div class="collapse navbar-collapse text-center" id="navbarsExample09">
				<%= form_with(url: site_search_path, local: true, method: :get, class: "form-inline") do |form|%>
					<%= form.text_field :term, class: "form-control mr-sm-2", type: "search", placeholder: "Search" %>
					<button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
				<% end %>
			<ul class="navbar-nav ml-auto">
			<% unless user_signed_in? %>
				<li class="nav-item active">
					<%= link_to 'Entrar', new_user_session_path , class:"nav-link"%>
			  </li>
			  <li class="nav-item">
					<%= link_to 'Cadastrar-se', new_user_registration_path, class: "nav-link"%>
				</li>
			<% else %>
			   <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown05">
						<%= link_to users_backoffice_welcome_index_path do %>
							<i class="dropdown-item">Perfil</i>
						<% end %>
						<%= link_to destroy_user_session_path, method: :delete do  %>
							<i class="dropdown-item">Sair</i>
						<% end %>
					</ul>
			  </li>
				<% end %>
			</ul>
		  </div>
		</div>
	</nav>
</header>
<div class="main-wrapper ">
<section class="slider">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 col-md-10">
				<div class="block">
					<span class="d-block mb-3 text-white text-capitalize">Aplicativo de Perguntas e respostas</span>
					<h1 class="animated fadeInUp mb-5">Our work is <br>presentation of our <br>capabilities.</h1>
				</div>
			</div>
		</div>
    <%= render partial: 'shared/questions' %>
	</div>	
</section>
    <!-- Main jQuery -->
    <script src="plugins/jquery/jquery.js"></script>
    <script src="js/contact.js"></script>
    <!-- Bootstrap 4.3.1 -->
    <script src="plugins/bootstrap/js/popper.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.min.js"></script>
   <!--  Magnific Popup-->
    <script src="plugins/magnific-popup/dist/jquery.magnific-popup.min.js"></script>
    <!-- Slick Slider -->
    <script src="plugins/slick-carousel/slick/slick.min.js"></script>
    <!-- Counterup -->
    <script src="plugins/counterup/jquery.waypoints.min.js"></script>
    <script src="plugins/counterup/jquery.counterup.min.js"></script>  
    
    <script src="js/script.js"></script>

</body>
</html>
   