config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    #com / o argumento ja é recebido no controller como subject_id
    get 'subject/:subject_id', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
  end

  namespace :admins_backoffice do
    get 'welcome/index' #Dashboard
    resources :admins
    resources :subjects
    resources :questions
  end
  
  #skip exclui rota para registrar novos admins 
  devise_for :admins, skip: [:registrations]
  devise_for :users
  
  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #Kaminari paginator
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  #atualiza o banco apos adicionar a coluna para contagem de assunto.(counter_cache)
  # x = Subject.last
  #Subject.reset_counters(x.id, :questions)

  has_many :answers

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  
  #paginates_per 8
  
  #scope são usadas quando é necessario fazer alguma pesquisa no model
  scope :list_questions_params, ->(page_params){
    Question.includes(:answers, :subject)
            .where('lower(description) LIKE ?', "%#{page_params.downcase}%")
  }
  
  scope :list_questions, ->{
    Question.includes(:answers, :subject)
            .order('created_at desc')
  }

  scope :list_subject_params, ->(page_params, subject_id){
    Question.includes(:answers, :subject)
            .where(subject_id: subject_id)
  }
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    [self.first_name, self.last_name].join(" ")
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller? && resource_class == Admin
      'admin_devise'
    elsif devise_controller? && resource_class == User
      'user_devise'
    else
      'application'
    end
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    admin_path
  end

end

app/controllers/site/answer_controller.rb
module Site
  class AnswerController < SiteController
    
    def question
      @answer = Answer.find(params[:answer_id])
    end
  end
end

app/controllers/site/search_controller.rb
module Site
  class SearchController < SiteController
    
    def questions
      questions = Question.list_questions_params(params[:term])

      @questions = paginate_questions(questions)
    end

    def subject
      questions = Question.list_subject_params(params[:term], params[:subject_id])

      @questions = paginate_questions(questions)
    end

    private

    def paginate_questions(questions)
      Kaminari.paginate_array(questions).page(params[:page]).per(8)
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admins/shared/_form.html.erb
<br>
<h1><%= "#{action_message} Administrador"%></h1>
<hr/>
<br>

<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <ul style="margin-bottom: 0rem !important;">
      <%@admin.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card">
  <div class="card-header">
  <%= "#{action_message} Administrador" %>
  </div> 
  <div class="card-body">
  <%# Por padrão as informações do forms são enviadas via JS, 'local: true' define para que seja enviado via HTML %>
    <%= form_with model: [:admins_backoffice, @admin], local: true do |form|%>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder:"Email adm" %>
        <small id="emailHelp" class="form-text text-muted">Nunca vamos compartilhar seu email, com ninguém.</small>
      </div>
      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder:"Password" %><br>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder:"Password-confirmation" %>
      </div>
      <button type="submit" class="btn btn-warning ">Salvar</button>
    <% end %>
  </div>
</div>

app/views/shared/_questions.html.erb
<% @questions.each do |question| %>
  <%= form_with url: site_answer_path do |form|%>
    <div class="card">
      <h5 class="card-header"><%= question.description %>
        <span class="badge badge-info ml-2">
          <%= link_to "#{question.subject.description} (#{question.subject.questions_count})", site_search_subject_path(question.subject_id), class: 'text-white' %>
        </span>
      </h5>
      <div class="card-body">
        <% question.answers.each do |answer|%>
          <div class="form-check">
            <label class="form-check-label">
              <%= radio_button_tag 'answer_id', answer.id %><%= answer.description %>
            </label>
          </div>
        <% end %>
        <br>
        <%= form.submit 'Responder', class: 'btn btn-primary', id: "submit_answer_#{question.id}" %>
      </div>
    </div>
    <br>
  <% end %>
<% end %>
<div class="d-flex justify-content-center mt-5">
  <%= paginate @questions %>
</div>